services:
  iwscan:
    build: .
    container_name: monitoring-iwscan-exporter
    privileged: true
    network_mode: host
    restart: unless-stopped
    environment:
      - INTERFACE=wlan0
      - PORT=5024